### ISSUE TITLE
Running a local version?

### ISSUE THREAD

**Issue by trainorpj** [brendena/MathEquationsGoogleSlide#1]
Hey there! I just used your add-on and really liked it.

I wanted to suggest some adjustments, but I couldn't get a local version running after I forked the repo.  Perhaps it's because I'm not familiar with elm.

How are you developing this locally?

**Comment by trainorpj** [comment]
I think I figured it out, although I still can't load `index.html` properly... I was hoping I could tweak the css 💅

**Comment by brendena** [comment]
The easiest way to make these types of changes would be to make a new chrome google slide extension and then pull the latest code from github using this [extension](https://chrome.google.com/webstore/detail/google-apps-script-github/lfjcgcmkmjjlieihflfhjopckgpelofo)

From there you can just edit the css inside of the index.html.  With the same extension, you can then push the code back to github.  Going this route you avoid the need to work with elm.

But if you want to build from the elm code I added a section in the readme.md to describe how to do that. 

If you don't know how to create a google slide extension just
1.  Create a new google Slide project
2.  Go to **Tools** in the menu and select  **Script Editor**

Sorry for the late response and have a nice day.

**Comment by trainorpj** [comment]
Thanks @brendena! If you don't mind, I might try it out and make another PR.

I found your add-on to work really well, and I was excited to see that it was open source 😀 Great work!

**Comment by brendena** [comment]
If your interested in this project, you might want to look at the next iteration of this idea.  I just created a chrome/firefox web extension that create a menu to build math equations with.
https://github.com/brendena/MathEquations-Extension

I do plan on continuing this google slides project.  This project is just limited by the fact that it's attached to a google slide. Also this was my first elm project.  So the code wasn't all that good.

**Comment by trainorpj** [comment]
Looks really cool. If I have some time this weekend I'll give it a look.  I'm pretty interested in working with elm, so this looks like a good project.

I'll let you know 😄
