### ISSUE TITLE
white text

### ISSUE THREAD

**Issue by bisraelsen** [brendena/MathEquationsGoogleSlide#3]
I would like to request that the output image be able to be white as well as black, to enable using dark-themed presentations.

In fact, enabling custom color would be even better... of course it might be difficult to add.

**Comment by brendena** [comment]
Very cool idea.

I just pushed the change to the chrome extension page.  It takes at least 5 days for google to review a google slide extensions.  I added a input of type "color" so you will be able to change the equation to what ever color you want.  Then i take this color value and i append it to a svg "color" style before i convert it to a image in canvas.  So it was a relatively easy to add on.
